SUPPORT_LANGUAGES = {'assembly': {'name': '.asm', 'url': 'https://run.glot.io/languages/assembly/latest'},
                     'ats': {'name': '.dats', 'url': 'https://run.glot.io/languages/ats/latest'},
                     'bash': {'name': '.sh', 'url': 'https://run.glot.io/languages/bash/latest'},
                     'c': {'name': '.c', 'url': 'https://run.glot.io/languages/c/latest'},
                     'clojure': {'name': '.clj', 'url': 'https://run.glot.io/languages/clojure/latest'},
                     'cobol': {'name': '.cob', 'url': 'https://run.glot.io/languages/cobol/latest'},
                     'coffeescript': {'name': '.coffee', 'url': 'https://run.glot.io/languages/coffeescript/latest'},
                     'cpp': {'name': '.cpp', 'url': 'https://run.glot.io/languages/cpp/latest'},
                     'c++': {'name': '.cpp', 'url': 'https://run.glot.io/languages/cpp/latest'},
                     'crystal': {'name': '.cr', 'url': 'https://run.glot.io/languages/crystal/latest'},
                     'csharp': {'name': '.cs', 'url': 'https://run.glot.io/languages/csharp/latest'},
                     'c#': {'name': '.cs', 'url': 'https://run.glot.io/languages/csharp/latest'},
                     'd': {'name': '.d', 'url': 'https://run.glot.io/languages/d/latest'},
                     'elixir': {'name': '.ex', 'url': 'https://run.glot.io/languages/elixir/latest'},
                     'elm': {'name': '.elm', 'url': 'https://run.glot.io/languages/elm/latest'},
                     'erlang': {'name': '.erl', 'url': 'https://run.glot.io/languages/erlang/latest'},
                     'fsharp': {'name': '.fs', 'url': 'https://run.glot.io/languages/fsharp/latest'},
                     'go': {'name': '.go', 'url': 'https://run.glot.io/languages/go/latest'},
                     'groovy': {'name': '.groovy', 'url': 'https://run.glot.io/languages/groovy/latest'},
                     'haskell': {'name': '.hs', 'url': 'https://run.glot.io/languages/haskell/latest'},
                     'idris': {'name': '.idr', 'url': 'https://run.glot.io/languages/idris/latest'},
                     'java': {'name': '.java', 'url': 'https://run.glot.io/languages/java/latest'},
                     'javascript': {'name': '.js', 'url': 'https://run.glot.io/languages/javascript/latest'},
                     'julia': {'name': '.jl', 'url': 'https://run.glot.io/languages/julia/latest'},
                     'kotlin': {'name': '.kt', 'url': 'https://run.glot.io/languages/kotlin/latest'},
                     'lua': {'name': '.lua', 'url': 'https://run.glot.io/languages/lua/latest'},
                     'mercury': {'name': '.m', 'url': 'https://run.glot.io/languages/mercury/latest'},
                     'nim': {'name': '.nim', 'url': 'https://run.glot.io/languages/nim/latest'},
                     'ocaml': {'name': '.ml', 'url': 'https://run.glot.io/languages/ocaml/latest'},
                     'perl': {'name': '.pl', 'url': 'https://run.glot.io/languages/perl/latest'},
                     'perl6': {'name': '.pl6', 'url': 'https://run.glot.io/languages/perl6/latest'},
                     'php': {'name': '.php', 'url': 'https://run.glot.io/languages/php/latest'},
                     'python': {'name': '.py', 'url': 'https://run.glot.io/languages/python/latest'},
                     'py': {'name': '.py', 'url': 'https://run.glot.io/languages/python/latest'},
                     'ruby': {'name': '.rb', 'url': 'https://run.glot.io/languages/ruby/latest'},
                     'rust': {'name': '.rs', 'url': 'https://run.glot.io/languages/rust/latest'},
                     'scala': {'name': '.scala', 'url': 'https://run.glot.io/languages/scala/latest'},
                     'swift': {'name': '.swift', 'url': 'https://run.glot.io/languages/swift/latest'},
                     'typescript': {'name': '.ts', 'url': 'https://run.glot.io/languages/typescript/latest'}}

HEADER = {"Authorization": "Token e4ea3127-cfc8-4d4d-94d0-00332929e834", "Content-type": "application/json"}

